In [ ]:
import torch
import numpy as np

x=torch.empty(5,3)
print(x)

tensor([[-9.4809e+01,  4.5666e-41, -9.4810e+01],
        [ 4.5666e-41, -9.4810e+01,  4.5666e-41],
        [-9.4838e+01,  4.5666e-41, -9.2881e+02],
        [ 4.5666e-41, -9.4622e+01,  4.5666e-41],
        [-9.4623e+01,  4.5666e-41, -9.4623e+01]])


In [ ]:
x=torch.rand(5,3)
print(x)

tensor([[0.3689, 0.2479, 0.7734],
        [0.0177, 0.7620, 0.6446],
        [0.0132, 0.6920, 0.0879],
        [0.1256, 0.0173, 0.0489],
        [0.3708, 0.0688, 0.0145]])


 创建一个5*3的long型全0的`Tensor`:

In [ ]:

x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
# 直接根据数据创建：
x=torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

通过现有的`Tensor`来创建，此方法会默认重用出入`Tensor`的一些属性，例如数据类型，除非指定数据类型

In [ ]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1394,  0.3068, -0.5704],
        [-1.5187, -0.0845, -0.0379],
        [ 1.0616,  1.2340, -0.4193],
        [-0.6699, -1.5956, -0.0672],
        [-0.5874, -1.6367,  0.4315]])


可以通过`shape`或者`size()`来获取`Tensor`的形状：
> 返回的`torch.Size`其实就是一个`tuple`，支持所有`tuple`的操作

In [ ]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [ ]:
y=torch.rand(5,3)
# 加法形式一
print(x+y)
# 加法形式二
print(torch.add(x,y))
# 可指定输出：
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)
# 加法形式三,inplace
y.add_(x)
print(y)

tensor([[ 1.4243,  0.8153,  0.3104],
        [-1.0119,  0.1839,  0.8331],
        [ 1.3431,  1.6235,  0.2781],
        [-0.4831, -1.1814,  0.3586],
        [ 0.2953, -1.2312,  0.4760]])
tensor([[ 1.4243,  0.8153,  0.3104],
        [-1.0119,  0.1839,  0.8331],
        [ 1.3431,  1.6235,  0.2781],
        [-0.4831, -1.1814,  0.3586],
        [ 0.2953, -1.2312,  0.4760]])
tensor([[ 1.4243,  0.8153,  0.3104],
        [-1.0119,  0.1839,  0.8331],
        [ 1.3431,  1.6235,  0.2781],
        [-0.4831, -1.1814,  0.3586],
        [ 0.2953, -1.2312,  0.4760]])
tensor([[ 1.4243,  0.8153,  0.3104],
        [-1.0119,  0.1839,  0.8331],
        [ 1.3431,  1.6235,  0.2781],
        [-0.4831, -1.1814,  0.3586],
        [ 0.2953, -1.2312,  0.4760]])


In [ ]:
# 用view()来改变Tensor形状
y=x.view(15)
z=x.view(-1,5)
print(x.shape,y.shape,z.shape)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


`view()`返回的新`Tensor`与源`Tensor`虽然有不同的`size`，但是共享数据，也即更改其中的一个，另一个也会跟着改变。（view仅仅是改变了对这个张量的观察角度，内部数据并未改变）
如果想要返回一个真正的副本（不共享内存），推荐先用`clone()`创造一个副本，然后再用`view()`

>使用`clone()`的另一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源`Tensor`

### 广播机制
当对两个形状不同的`Tensor`按元素运算时，可能会出发广播（broadcasting)机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。

In [ ]:
x=torch.arange(1,3).view(1,2)
print(x)
y=torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### `Tensor`和Numpy相互转换
可以通过`numpy()`和`from_numpy()`将`Tensor`和Numpy中的数组相互转换。但是：**这两个函数所产生的`Tensor`和Numpy中的数组共享相同的内存**
> 还有一个常用的将Numpy的array转换成`Tensor`的方法是`torch.tensor()`，此方法总是会进行数据拷贝。

In [ ]:
a=torch.ones(5)
b=a.numpy()
print(a,b)
a+=1
print(a,b)
b+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [ ]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)
b+=1
print(a,b)

c=torch.tensor(a)
a+=1
print(a,c)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d7fbb927-f409-443e-9b59-e37fbc464df5' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>